### ISSUE TITLE
FeatureRequest: provide as pip or bioconda package

### ISSUE THREAD

**Issue by Leon-Bichmann** [duolinwang/DM3Loc#1]
Hey,
really nice work would be great if it was available as pip or conda package.

**Comment by duolinwang** [comment]
Thank you for your comment. But we have no plan to modify or release this code as a pip or bioconda package. That needs a lot of work. We are currently short-handed.
________________________________
From: Leon-Bichmann ***@***.***>
Sent: Thursday, September 22, 2022 9:54
To: duolinwang/DM3Loc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [duolinwang/DM3Loc] FeatureRequest: provide as pip or bioconda package (Issue #1)

WARNING: This message has originated from an External Source. This may be a phishing expedition that can result in unauthorized access to our IT System. Please use proper judgment and caution when opening attachments, clicking links, or responding to this email.

Hey,
really nice work would be great if it was available as pip or conda package.

**Comment by Leon-Bichmann** [comment]
Thanks for the answer, this is unfortunate but I can see the additional effort. Closing this issue again.
