### ISSUE TITLE
Question about the label of mRNA subcellular localization. 

### ISSUE THREAD

**Issue by jaminzzz** [duolinwang/DM3Loc#2]
Hello, awesome work for mRNA subcellular localization! May I ask why there are only six classes of mRNA subcellular localization in total, but the label in the data set is a seven-dimensional vector, such as **1100001**?

**Comment by duolinwang** [comment]
Hello,

The additional dimension is to represent "none" which is a class that does not belong to any of the six classes.

Duolin
________________________________
From: jaminzzz ***@***.***>
Sent: Wednesday, November 8, 2023 21:15
To: duolinwang/DM3Loc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [duolinwang/DM3Loc] Question about the label of mRNA subcellular localization. (Issue #2)

WARNING: This message has originated from an External Source. This may be a phishing expedition that can result in unauthorized access to our IT System. Please use proper judgment and caution when opening attachments, clicking links, or responding to this email.

Hello, awesome work for mRNA subcellular localization! May I ask why there are only six classes of mRNA subcellular localization in total, but the label in the data set is a seven-dimensional vector, such as 1100001?

**Comment by jaminzzz** [comment]
@duolinwang Got it, thank you very much for the reply!
